/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

import java.io.File;
import java.io.IOException;
import java.util.*;

/**
 *
 * @author USUARIO
 */
public class frmAtenderCita extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAtenderCita.class.getName());


    private String idCita;
    private String nombrePaciente;
    private List<String[]> medicinas; 
    private boolean citaAtendida = false; 
    private String estadoCita = "";

    
        /**
     * Creates new form frmAtenderCita
     */
    public frmAtenderCita(String idCita, String nombrePaciente) {
        this.idCita = idCita;
        this.nombrePaciente = nombrePaciente;
        this.medicinas = new ArrayList<>();
        initComponents();
        lIdCita.setText("ID Cita: " + idCita);
        lPaciente.setText("Paciente: " + nombrePaciente);
    }
    
    private void generarArchivoConsulta() {
    try {
        String nombreArchivo = String.format("Consulta_%s_%s.txt", 
            this.idCita, 
            new java.text.SimpleDateFormat("yyyyMMdd_HHmmss").format(new java.util.Date()));
        
        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(nombreArchivo))) {
            pw.println("═══════════════════════════════════════════════════════════");
            pw.println("              REGISTRO DE CONSULTA MÉDICA");
            pw.println("═══════════════════════════════════════════════════════════");
            pw.println();
            
            pw.println("ID CITA: " + this.idCita);
            pw.println("PACIENTE: " + this.nombrePaciente);
            pw.println("FECHA DE REGISTRO: " + new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date()));
            pw.println();
            
            pw.println("───────────────────────────────────────────────────────────");
            pw.println("INFORMACIÓN CLÍNICA");
            pw.println("───────────────────────────────────────────────────────────");
            pw.println();
            
            pw.println("GRAVEDAD: " + cmbGravedad.getSelectedItem());
            pw.println();
            
            pw.println("DIAGNÓSTICO:");
            pw.println(txtDiagnostico.getText().trim());
            pw.println();
            
            pw.println("TRATAMIENTO:");
            pw.println(txtTratamiento.getText().trim());
            pw.println();
            
            pw.println("DURACIÓN DEL TRATAMIENTO: " + spnDuracion.getValue() + " días");
            pw.println();
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaMedicinas.getModel();
            if (chkReceta.isSelected() && modelo.getRowCount() > 0) {
                pw.println("───────────────────────────────────────────────────────────");
                pw.println("PRESCRIPCIÓN DE MEDICAMENTOS");
                pw.println("───────────────────────────────────────────────────────────");
                pw.println();
                
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    String med = modelo.getValueAt(i, 0).toString();
                    String dosis = modelo.getValueAt(i, 1).toString();
                    String indic = modelo.getValueAt(i, 2).toString();
                    
                    pw.println((i + 1) + ". " + med);
                    pw.println("   Dosis: " + dosis);
                    pw.println("   Indicaciones: " + indic);
                    pw.println();
                }
            } else {
                pw.println("No se prescribieron medicamentos.");
                pw.println();
            }
            
            pw.println("═══════════════════════════════════════════════════════════");
            pw.println("           Fin del Registro de Consulta");
            pw.println("═══════════════════════════════════════════════════════════");
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Archivo generado exitosamente:\n" + nombreArchivo,
            "Archivo Creado", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al generar el archivo: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEncabezadoACM = new javax.swing.JPanel();
        lAtencionConsultaM = new javax.swing.JLabel();
        lIdCita = new javax.swing.JLabel();
        lPaciente = new javax.swing.JLabel();
        pPrincipalACM = new javax.swing.JPanel();
        jGravedad = new javax.swing.JLabel();
        cmbGravedad = new javax.swing.JComboBox<>();
        jDiagnostico = new javax.swing.JLabel();
        scrpDiagnostico = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        lTratamiento = new javax.swing.JLabel();
        scrpTratamiento = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();
        lDuracion = new javax.swing.JLabel();
        spnDuracion = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        chkReceta = new javax.swing.JCheckBox();
        lMedicamento = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        lDosis = new javax.swing.JLabel();
        txtDosis = new javax.swing.JTextField();
        lIndicaciones = new javax.swing.JLabel();
        txtIndicaciones = new javax.swing.JTextField();
        btnAgregarMedicina = new javax.swing.JButton();
        scrpMedicamentos = new javax.swing.JScrollPane();
        tablaMedicinas = new javax.swing.JTable();
        btnEliminarMedicina = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNoSePresento = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atender Cita");
        setPreferredSize(new java.awt.Dimension(760, 815));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pEncabezadoACM.setBackground(new java.awt.Color(70, 130, 180));
        pEncabezadoACM.setMinimumSize(new java.awt.Dimension(760, 120));
        pEncabezadoACM.setPreferredSize(new java.awt.Dimension(760, 120));
        pEncabezadoACM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lAtencionConsultaM.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lAtencionConsultaM.setForeground(new java.awt.Color(255, 255, 255));
        lAtencionConsultaM.setText("ATENCIÓN DE CONSULTA MÉDICA");
        lAtencionConsultaM.setPreferredSize(new java.awt.Dimension(500, 27));
        pEncabezadoACM.add(lAtencionConsultaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        lIdCita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lIdCita.setForeground(new java.awt.Color(255, 255, 255));
        lIdCita.setText("ID Cita: ");
        lIdCita.setPreferredSize(new java.awt.Dimension(300, 25));
        pEncabezadoACM.add(lIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lPaciente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lPaciente.setForeground(new java.awt.Color(255, 255, 255));
        lPaciente.setText("Paciente: ");
        lPaciente.setPreferredSize(new java.awt.Dimension(500, 22));
        pEncabezadoACM.add(lPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(pEncabezadoACM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pPrincipalACM.setBackground(new java.awt.Color(255, 255, 255));
        pPrincipalACM.setPreferredSize(new java.awt.Dimension(740, 600));
        pPrincipalACM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jGravedad.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jGravedad.setText("Gravedad: ");
        jGravedad.setPreferredSize(new java.awt.Dimension(100, 25));
        pPrincipalACM.add(jGravedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        cmbGravedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leve", "Moderada", "Grave", "Crítica" }));
        cmbGravedad.setPreferredSize(new java.awt.Dimension(150, 25));
        pPrincipalACM.add(cmbGravedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 160, -1));

        jDiagnostico.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jDiagnostico.setText("Diagnóstico: ");
        jDiagnostico.setPreferredSize(new java.awt.Dimension(120, 25));
        pPrincipalACM.add(jDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        scrpDiagnostico.setPreferredSize(new java.awt.Dimension(700, 70));

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(3);
        scrpDiagnostico.setViewportView(txtDiagnostico);

        pPrincipalACM.add(scrpDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));

        lTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lTratamiento.setText("Tratamiento: ");
        lTratamiento.setPreferredSize(new java.awt.Dimension(120, 25));
        pPrincipalACM.add(lTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, -1, -1));

        scrpTratamiento.setPreferredSize(new java.awt.Dimension(700, 70));

        txtTratamiento.setColumns(20);
        txtTratamiento.setRows(3);
        scrpTratamiento.setViewportView(txtTratamiento);

        pPrincipalACM.add(scrpTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lDuracion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lDuracion.setText("Duración (días): ");
        lDuracion.setPreferredSize(new java.awt.Dimension(120, 25));
        pPrincipalACM.add(lDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        spnDuracion.setModel(new javax.swing.SpinnerNumberModel(7, 1, 365, 1));
        spnDuracion.setPreferredSize(new java.awt.Dimension(80, 25));
        pPrincipalACM.add(spnDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PRESCRIPCIÓN DE MEDICAMENTOS: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(500, 25));
        pPrincipalACM.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, -1));

        chkReceta.setText("Preescribir Medicamentos");
        chkReceta.setPreferredSize(new java.awt.Dimension(200, 25));
        chkReceta.addActionListener(this::chkRecetaActionPerformed);
        pPrincipalACM.add(chkReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lMedicamento.setText("Medicamento: ");
        lMedicamento.setPreferredSize(new java.awt.Dimension(100, 25));
        pPrincipalACM.add(lMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 365, -1, -1));

        txtMedicamento.setEnabled(false);
        txtMedicamento.setPreferredSize(new java.awt.Dimension(200, 25));
        pPrincipalACM.add(txtMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 365, -1, -1));

        lDosis.setText("Dosis: ");
        lDosis.setPreferredSize(new java.awt.Dimension(50, 25));
        pPrincipalACM.add(lDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 365, -1, -1));

        txtDosis.setEnabled(false);
        txtDosis.setPreferredSize(new java.awt.Dimension(150, 25));
        pPrincipalACM.add(txtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 365, -1, -1));

        lIndicaciones.setText("Indicaciones: ");
        lIndicaciones.setPreferredSize(new java.awt.Dimension(100, 25));
        pPrincipalACM.add(lIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        txtIndicaciones.setEnabled(false);
        txtIndicaciones.setPreferredSize(new java.awt.Dimension(400, 25));
        pPrincipalACM.add(txtIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        btnAgregarMedicina.setBackground(new java.awt.Color(60, 179, 113));
        btnAgregarMedicina.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMedicina.setText("Agregar");
        btnAgregarMedicina.setEnabled(false);
        btnAgregarMedicina.setFocusPainted(false);
        btnAgregarMedicina.setPreferredSize(new java.awt.Dimension(90, 23));
        btnAgregarMedicina.addActionListener(this::btnAgregarMedicinaActionPerformed);
        pPrincipalACM.add(btnAgregarMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        scrpMedicamentos.setPreferredSize(new java.awt.Dimension(700, 120));

        tablaMedicinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "Dosis", "Indicaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrpMedicamentos.setViewportView(tablaMedicinas);

        pPrincipalACM.add(scrpMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 435, -1, -1));

        btnEliminarMedicina.setBackground(new java.awt.Color(220, 20, 60));
        btnEliminarMedicina.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMedicina.setText("Eliminar");
        btnEliminarMedicina.setEnabled(false);
        btnEliminarMedicina.setFocusPainted(false);
        btnEliminarMedicina.setPreferredSize(new java.awt.Dimension(90, 23));
        btnEliminarMedicina.addActionListener(this::btnEliminarMedicinaActionPerformed);
        pPrincipalACM.add(btnEliminarMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        getContentPane().add(pPrincipalACM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(220, 20, 60));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(131, 27));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 750, 100, 30));

        btnNoSePresento.setBackground(new java.awt.Color(255, 140, 0));
        btnNoSePresento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNoSePresento.setForeground(new java.awt.Color(255, 255, 255));
        btnNoSePresento.setText("No se presentó");
        btnNoSePresento.setFocusPainted(false);
        btnNoSePresento.addActionListener(this::btnNoSePresentoActionPerformed);
        getContentPane().add(btnNoSePresento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 750, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(60, 179, 113));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 750, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRecetaActionPerformed
        // TODO add your handling code here:
    boolean habilitado = chkReceta.isSelected();
    txtMedicamento.setEnabled(habilitado);
    txtDosis.setEnabled(habilitado);
    txtIndicaciones.setEnabled(habilitado);
    btnAgregarMedicina.setEnabled(habilitado);
    btnEliminarMedicina.setEnabled(habilitado);
    }//GEN-LAST:event_chkRecetaActionPerformed

    private void btnAgregarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicinaActionPerformed
        // TODO add your handling code here:
    String medicamento = txtMedicamento.getText().trim();
    String dosis = txtDosis.getText().trim();
    String indicaciones = txtIndicaciones.getText().trim();
    
    if (medicamento.isEmpty() || dosis.isEmpty() || indicaciones.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos del medicamento");
        return;
    }
    
    // Validar que la dosis sea un número mayor a 1
    try {
        int valorDosis = Integer.parseInt(dosis);
        if (valorDosis < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La dosis debe ser un número mayor o igual a 1", 
                "Error de validación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtDosis.requestFocus();
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "La dosis debe ser un número válido", 
            "Error de validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        txtDosis.requestFocus();
        return;
    }
    
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) tablaMedicinas.getModel();
    modelo.addRow(new Object[]{medicamento, dosis, indicaciones});
    
    // Limpiar campos
    txtMedicamento.setText("");
    txtDosis.setText("");
    txtIndicaciones.setText("");
    txtMedicamento.requestFocus();
    }//GEN-LAST:event_btnAgregarMedicinaActionPerformed

    private void btnEliminarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedicinaActionPerformed
        // TODO add your handling code here:
    int fila = tablaMedicinas.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un medicamento para eliminar");
        return;
    }
    
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) tablaMedicinas.getModel();
    modelo.removeRow(fila);
    }//GEN-LAST:event_btnEliminarMedicinaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        citaAtendida = false;
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNoSePresentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoSePresentoActionPerformed
        // TODO add your handling code here:
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Confirma que el paciente no se presentó a la cita?", 
        "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        citaAtendida = true;
        estadoCita = "No se presentó";
        javax.swing.JOptionPane.showMessageDialog(this, "Cita marcada como 'No se presentó'");
        dispose();
    }
    }//GEN-LAST:event_btnNoSePresentoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    if (txtDiagnostico.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un diagnóstico");
        return;
    }

    if (txtTratamiento.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el tratamiento");
        return;
    }

    String archivoRecetas = "recetas.csv";
    
    StringBuilder mensaje = new StringBuilder("CONSULTA REGISTRADA\n\n");
    mensaje.append("Gravedad: ").append(cmbGravedad.getSelectedItem()).append("\n");
    mensaje.append("Duración: ").append(spnDuracion.getValue()).append(" días\n");

    try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(archivoRecetas, true))) {
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaMedicinas.getModel();
        
        if (chkReceta.isSelected() && modelo.getRowCount() > 0) {
            mensaje.append("\nMedicamentos prescritos:\n");
            
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String med = modelo.getValueAt(i, 0).toString();
                String dosis = modelo.getValueAt(i, 1).toString();
                String indic = modelo.getValueAt(i, 2).toString();
                
                String linea = String.format("%s,%s,%s,%s,%s", 
                        this.idCita, this.nombrePaciente, med, dosis, "Pendiente");
                bw.write(linea);
                bw.newLine();
                
                mensaje.append("  • ").append(med).append(" - ").append(dosis)
                       .append(" (").append(indic).append(")\n");
            }
        }
        
        citaAtendida = true;
        estadoCita = "Atendida";
        
        generarArchivoConsulta();

        javax.swing.JOptionPane.showMessageDialog(this, mensaje.toString(), 
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        dispose();

    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la receta: " + e.getMessage());
    }
   
    }//GEN-LAST:event_btnGuardarActionPerformed

    public boolean isCitaAtendida() {
        return citaAtendida;
    }
    
    public String getEstadoCita() {
        return estadoCita;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(frmAtenderCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new frmAtenderCita("C001", "Juan Pérez").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicina;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarMedicina;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNoSePresento;
    private javax.swing.JCheckBox chkReceta;
    private javax.swing.JComboBox<String> cmbGravedad;
    private javax.swing.JLabel jDiagnostico;
    private javax.swing.JLabel jGravedad;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lAtencionConsultaM;
    private javax.swing.JLabel lDosis;
    private javax.swing.JLabel lDuracion;
    private javax.swing.JLabel lIdCita;
    private javax.swing.JLabel lIndicaciones;
    private javax.swing.JLabel lMedicamento;
    private javax.swing.JLabel lPaciente;
    private javax.swing.JLabel lTratamiento;
    private javax.swing.JPanel pEncabezadoACM;
    private javax.swing.JPanel pPrincipalACM;
    private javax.swing.JScrollPane scrpDiagnostico;
    private javax.swing.JScrollPane scrpMedicamentos;
    private javax.swing.JScrollPane scrpTratamiento;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JTable tablaMedicinas;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtIndicaciones;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextArea txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
