package pack_gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class frmFarmaceutico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmFarmaceutico.class.getName());

    private void inicializarInventario() {
    java.io.File archivo = new java.io.File("inventario.csv");
    if (!archivo.exists()) {
        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
            // Encabezados y medicinas por defecto
            pw.println("MEDICINA,STOCK");
            pw.println("Paracetamol,100");
            pw.println("Ibuprofeno,50");
            pw.println("Amoxicilina,30");
            pw.println("Omeprazol,20");
            pw.println("Vitamina C,200");
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al crear inventario inicial");
        }
    }
}
    private void cargarTablas() {
    javax.swing.table.DefaultTableModel modRecetas = (javax.swing.table.DefaultTableModel) tablaR.getModel();
    javax.swing.table.DefaultTableModel modMedicina = (javax.swing.table.DefaultTableModel) tablaM.getModel();
    
    // Limpiar tablas antes de cargar
    modRecetas.setRowCount(0);
    modMedicina.setRowCount(0);

    //Cargar Recetas Pendientes
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("recetas.csv"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            
            if (datos[4].equalsIgnoreCase("Pendiente")) {
                modRecetas.addRow(new Object[]{datos[0], datos[1], datos[2], datos[3]});
            }
        }
    } catch (Exception e) { /* El archivo puede no existir aún si no hay recetas */ }

 
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("inventario.csv"))) {
        String linea;
        br.readLine(); // Salta el encabezado (MEDICINA,STOCK)
        while ((linea = br.readLine()) != null) {
            modMedicina.addRow(linea.split(","));
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al leer inventario");
    }
}
    
    /**
     * Creates new form frmFarmaceutico
     */
    public frmFarmaceutico() {
        initComponents();
        inicializarInventario(); // Crea las medicinas si no existen
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaR = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaM = new javax.swing.JTable();
        bDespacharMedicina = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_CITA", "PACIENTE", "MEDICAMENTO", "DOSIS", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(tablaR);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recetas", jPanel2);

        tablaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicina", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tablaM);

        bDespacharMedicina.setText("Despachar Medicina");
        bDespacharMedicina.addActionListener(this::bDespacharMedicinaActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bDespacharMedicina)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(bDespacharMedicina)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medicina", jPanel3);

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido Farmacéutico");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestión Médica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTablaRecetas() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaR.getModel();
        java.io.File archivo = new java.io.File("recetas.csv");

        if (!archivo.exists()) return;

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            java.util.List<Object[]> datosNuevos = new java.util.ArrayList<>();
            String linea;

            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) continue;
                String[] campos = linea.split(",");

                // Verificamos que sea una receta pendiente (ID, Paciente, Medicina, Dosis, Estado)
                if (campos.length >= 5 && campos[4].trim().equalsIgnoreCase("Pendiente")) {
                    datosNuevos.add(new Object[]{campos[0], campos[1], campos[2], campos[3], campos[4]});
                }
            }

            // Solo limpiamos y llenamos si logramos leer el archivo correctamente
            modelo.setRowCount(0);
            for (Object[] fila : datosNuevos) {
                modelo.addRow(fila);
            }
        } catch (java.io.IOException e) {
            System.err.println("Error al cargar recetas: " + e.getMessage());
        }
    }
    
    private void actualizarTablaInventario() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaM.getModel();
        java.io.File archivo = new java.io.File("inventario.csv");

        if (!archivo.exists()) {
            inicializarInventario(); // Crea el archivo base si no existe
        }

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            java.util.List<String[]> filasInv = new java.util.ArrayList<>();
            String linea = br.readLine(); // Saltar encabezado: MEDICINA,STOCK

            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) continue;
                String[] datos = linea.split(",");
                if (datos.length == 2) {
                    filasInv.add(datos);
                }
            }

            // Actualización "atómica" para evitar que la tabla desaparezca
            modelo.setRowCount(0);
            for (String[] fila : filasInv) {
                modelo.addRow(fila);
            }
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer inventario: " + e.getMessage());
        }
    }
    
    private void bDespacharMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDespacharMedicinaActionPerformed
        String nombreMedicina = javax.swing.JOptionPane.showInputDialog(this, 
            "Ingrese el nombre de la medicina:", "Despachar Medicina", 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (nombreMedicina == null || nombreMedicina.trim().isEmpty()) return;
        nombreMedicina = nombreMedicina.trim();

        String strCantidad = javax.swing.JOptionPane.showInputDialog(this, 
                "Ingrese la cantidad a añadir al stock:", "Cantidad", 
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (strCantidad == null || strCantidad.trim().isEmpty()) return;

        int cantidadNueva;
        try {
            cantidadNueva = Integer.parseInt(strCantidad.trim());
            if (cantidadNueva <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida.");
            return;
        }

        java.io.File archivo = new java.io.File("inventario.csv");
        java.util.Map<String, Integer> inventario = new java.util.LinkedHashMap<>();
        boolean medicinaEncontrada = false;

        //Lectura del estado actual
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea = br.readLine(); // Encabezado
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length == 2) {
                    String med = datos[0];
                    int stock = Integer.parseInt(datos[1]);
                    if (med.equalsIgnoreCase(nombreMedicina)) {
                        stock += cantidadNueva;
                        medicinaEncontrada = true;
                    }
                    inventario.put(med, stock);
                }
            }
        } catch (java.io.IOException e) {}//Manejo de errores

        if (!medicinaEncontrada) {
            String nombreNormalizado = nombreMedicina.substring(0, 1).toUpperCase() + 
                                      nombreMedicina.substring(1).toLowerCase();
            inventario.put(nombreNormalizado, cantidadNueva);
        }

        // Escritura en el archivo y cierre
        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
            pw.println("MEDICINA,STOCK");
            for (java.util.Map.Entry<String, Integer> entry : inventario.entrySet()) {
                pw.println(entry.getKey() + "," + entry.getValue());
            }
            // El archivo se cierra automáticamente al salir de este bloque 'try'
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar.");
        }

        //Actualización visual de la interfaz
        actualizarTablaInventario(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Inventario actualizado correctamente.");
    }//GEN-LAST:event_bDespacharMedicinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmFarmaceutico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDespacharMedicina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaM;
    private javax.swing.JTable tablaR;
    // End of variables declaration//GEN-END:variables
}
