/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class frmlogin extends javax.swing.JFrame {
    
    private HashMap<String, String> credenciales = new HashMap<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmlogin.class.getName());

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        cargarDatosCSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondoLogin = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        iLogin = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        lcontrasena = new javax.swing.JLabel();
        bIniciarsesion = new javax.swing.JButton();
        bCrearCuenta = new javax.swing.JButton();
        tUsuario = new javax.swing.JTextField();
        pContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pFondoLogin.setBackground(new java.awt.Color(153, 153, 255));

        lLogin.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lLogin.setText("LOGIN");

        iLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        iLogin.setText("jLabel2");

        lUsuario.setText("USUARIO");

        lcontrasena.setText("CONTRASEÑA");

        bIniciarsesion.setText("INICIAR SESIÓN");
        bIniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bIniciarsesionMouseClicked(evt);
            }
        });
        bIniciarsesion.addActionListener(this::bIniciarsesionActionPerformed);

        bCrearCuenta.setText("CREAR CUENTA");
        bCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCrearCuentaMouseClicked(evt);
            }
        });

        tUsuario.addActionListener(this::tUsuarioActionPerformed);

        pContrasena.addActionListener(this::pContrasenaActionPerformed);

        javax.swing.GroupLayout pFondoLoginLayout = new javax.swing.GroupLayout(pFondoLogin);
        pFondoLogin.setLayout(pFondoLoginLayout);
        pFondoLoginLayout.setHorizontalGroup(
            pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLoginLayout.createSequentialGroup()
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLoginLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(iLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFondoLoginLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lLogin))
                    .addGroup(pFondoLoginLayout.createSequentialGroup()
                        .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFondoLoginLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lcontrasena))
                            .addGroup(pFondoLoginLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lUsuario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLoginLayout.createSequentialGroup()
                                    .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bCrearCuenta)
                                        .addComponent(bIniciarsesion))
                                    .addGap(63, 63, 63))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pFondoLoginLayout.setVerticalGroup(
            pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLogin)
                .addGap(9, 9, 9)
                .addComponent(iLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuario)
                    .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcontrasena)
                    .addComponent(pContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(bIniciarsesion)
                .addGap(18, 18, 18)
                .addComponent(bCrearCuenta)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bIniciarsesionActionPerformed

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void pContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pContrasenaActionPerformed

    private void bIniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarsesionMouseClicked
        String user = tUsuario.getText().trim().toLowerCase();
    String pass = new String(pContrasena.getPassword());

    if (credenciales.containsKey(user) && credenciales.get(user).equals(pass)) {
        
        String typeUser = "";
        String nombreUsuario = "";
        
        if (user.contains("_")) {
            int posicionInicio = user.lastIndexOf("_") + 1;
            int posicionFin = user.indexOf("@");
            typeUser = user.substring(posicionInicio, posicionFin);
            
            // Extraer nombre del usuario
            nombreUsuario = user.substring(0, user.indexOf("_"));
            nombreUsuario = nombreUsuario.replace(".", " ");
            nombreUsuario = nombreUsuario.substring(0, 1).toUpperCase() + nombreUsuario.substring(1);
        }

        switch (typeUser) {
            case "doctor":
                JOptionPane.showMessageDialog(this, "Bienvenido, Doctor. Sus consultas del día están listas.");
                frmMedico ventanaMedico = new frmMedico("Dr. " + nombreUsuario);
                ventanaMedico.setVisible(true);
                ventanaMedico.setLocationRelativeTo(null);
                this.dispose();
                break;
            case "paciente":
                JOptionPane.showMessageDialog(this, "Hola. Aquí puedes revisar tus citas médicas y recetas.");
                break;
            case "farmaceutico":
                JOptionPane.showMessageDialog(this, "Acceso concedido. Inventario de farmacia disponible.");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Bienvenido al sistema Vital-Core.");
                break;
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de Acceso", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bIniciarsesionMouseClicked

    private void bCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCrearCuentaMouseClicked
        frmregistro ventanaRegistro = new frmregistro(); 
        ventanaRegistro.setVisible(true); 
        ventanaRegistro.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_bCrearCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    
    private void cargarDatosCSV() {
        File archivo = new File("usuarios.csv");
        if (!archivo.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            br.readLine(); // Salto de la cabecera (usuario,contraseña)
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length == 2) {
                    credenciales.put(datos[0], datos[1]);
                }
            }
        } catch (IOException e) {
            System.err.println("Error al cargar: " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmlogin().setVisible(true);
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearCuenta;
    private javax.swing.JButton bIniciarsesion;
    private javax.swing.JLabel iLogin;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JLabel lcontrasena;
    private javax.swing.JPasswordField pContrasena;
    private javax.swing.JPanel pFondoLogin;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
