/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

/**
 *
 * @author USUARIO
 */
public class frmMedico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMedico.class.getName());
    
    private String nombreMedico;
    
        /**
     * Creates new form frmMedic
     */    
    
    public frmMedico() {
        this("Dr. Médico");
    }
    
    public frmMedico(String nombreMedico) {
        this.nombreMedico = nombreMedico;
        initComponents();
        lBienvenida.setText("Bienvenido, " + nombreMedico);
        cargarDatosEjemplo();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lBienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasAgendadas = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitasAtendidas = new javax.swing.JTable();
        btnVerDetalles = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Médico");
        setPreferredSize(new java.awt.Dimension(950, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lBienvenida.setText("Bienvenido Dr. Médico");
        lBienvenida.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel1.add(lBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Gestión Médica");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(930, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 360));

        tablaCitasAgendadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAgendadas.setRowHeight(25);
        jScrollPane1.setViewportView(tablaCitasAgendadas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnRefrescar.setBackground(new java.awt.Color(100, 149, 237));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setFocusPainted(false);
        btnRefrescar.setPreferredSize(new java.awt.Dimension(110, 35));
        btnRefrescar.addActionListener(this::btnRefrescarActionPerformed);
        jPanel2.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        btnAtender.setBackground(new java.awt.Color(60, 179, 113));
        btnAtender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("Atender Cita");
        btnAtender.setFocusPainted(false);
        btnAtender.setPreferredSize(new java.awt.Dimension(110, 35));
        btnAtender.addActionListener(this::btnAtenderActionPerformed);
        jPanel2.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 120, -1));

        jTabbedPane1.addTab("CItas Agendadas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(900, 360));

        tablaCitasAtendidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAtendidas.setRowHeight(25);
        jScrollPane2.setViewportView(tablaCitasAtendidas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnVerDetalles.setBackground(new java.awt.Color(100, 149, 237));
        btnVerDetalles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalles.setText("Ver Detalles");
        btnVerDetalles.setFocusPainted(false);
        btnVerDetalles.setPreferredSize(new java.awt.Dimension(100, 35));
        btnVerDetalles.addActionListener(this::btnVerDetallesActionPerformed);
        jPanel3.add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 110, -1));

        jTabbedPane1.addTab("Citas Atendidas", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(220, 20, 60));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(130, 25));
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        // TODO add your handling code here:
        atenderCita();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        cargarCitasAgendadas();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        // TODO add your handling code here:
        verDetalles();
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    
    private void cargarDatosEjemplo() {
        // Datos de ejemplo para Citas Agendadas
        javax.swing.table.DefaultTableModel modelo1 = 
            (javax.swing.table.DefaultTableModel) tablaCitasAgendadas.getModel();
        modelo1.addRow(new Object[]{"C001", "2026-01-18", "09:00", "Juan Pérez", "Chequeo general", "Agendada"});
        modelo1.addRow(new Object[]{"C002", "2026-01-18", "10:30", "María García", "Dolor abdominal", "Agendada"});
        modelo1.addRow(new Object[]{"C003", "2026-01-19", "14:00", "Carlos López", "Control presión", "Agendada"});
        
        // Datos de ejemplo para Citas Atendidas
        javax.swing.table.DefaultTableModel modelo2 = 
            (javax.swing.table.DefaultTableModel) tablaCitasAtendidas.getModel();
        modelo2.addRow(new Object[]{"C100", "2026-01-15", "09:00", "Pedro Sánchez", "Dolor cabeza", "Atendida"});
        modelo2.addRow(new Object[]{"C101", "2026-01-16", "15:00", "Laura Fernández", "Control diabetes", "Atendida"});
    }
    
    private void cargarCitasAgendadas() {
        javax.swing.JOptionPane.showMessageDialog(this, "Citas actualizadas");
    }
    
    private void atenderCita() {
 int fila = tablaCitasAgendadas.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cita para atender");
        return;
    }
    
    String idCita = (String) tablaCitasAgendadas.getValueAt(fila, 0);
    String paciente = (String) tablaCitasAgendadas.getValueAt(fila, 3);
    
    frmAtenderCita ventana = new frmAtenderCita(idCita, paciente);
    ventana.setVisible(true);
    ventana.setLocationRelativeTo(this);
    
    // Esperar a que se cierre la ventana y actualizar la tabla
    ventana.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            // Solo mover la cita si fue atendida
            if (ventana.isCitaAtendida()) {
                // Obtener los datos de la fila
                Object[] datosCita = new Object[6];
                for (int i = 0; i < 6; i++) {
                    datosCita[i] = tablaCitasAgendadas.getValueAt(fila, i);
                }
                
                // Cambiar el estado
                datosCita[5] = ventana.getEstadoCita(); // "Atendida" o "No se presentó"
                
                // Mover a la tabla de atendidas
                javax.swing.table.DefaultTableModel modeloAtendidas = 
                    (javax.swing.table.DefaultTableModel) tablaCitasAtendidas.getModel();
                modeloAtendidas.addRow(datosCita);
                
                // Eliminar de la tabla de agendadas
                javax.swing.table.DefaultTableModel modeloAgendadas = 
                    (javax.swing.table.DefaultTableModel) tablaCitasAgendadas.getModel();
                modeloAgendadas.removeRow(fila);
                
                javax.swing.JOptionPane.showMessageDialog(frmMedico.this, 
                    "Cita actualizada correctamente");
            }
        }
    });
    }
    
    private void verDetalles() {
        int fila = tablaCitasAtendidas.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cita para ver detalles");
            return;
        }
        
        String idCita = (String) tablaCitasAtendidas.getValueAt(fila, 0);
        String paciente = (String) tablaCitasAtendidas.getValueAt(fila, 3);
        String fecha = tablaCitasAtendidas.getValueAt(fila, 1).toString();
        
        String detalles = String.format(
            "DETALLES DE LA CITA\n\n" +
            "ID: %s\nPaciente: %s\nFecha: %s",
            idCita, paciente, fecha
        );
        
        javax.swing.JOptionPane.showMessageDialog(this, detalles, 
            "Detalles", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void cerrarSesion() {
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Está seguro que desea cerrar sesión?", 
        "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // Crear y mostrar ventana de login
        frmlogin login = new frmlogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        
        // Cerrar la ventana actual de médico
        this.dispose();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(frmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new frmMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JTable tablaCitasAgendadas;
    private javax.swing.JTable tablaCitasAtendidas;
    // End of variables declaration//GEN-END:variables
}
