/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

import pack_logica.Cita;
import java.sql.Time;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class frmMedico extends javax.swing.JFrame {
    
    private List<CitaConcreta> citasAgendadas;
    private List<CitaConcreta> citasAtendidas;
    private String nombreMedico;

    /**
     * Creates new form frmMedico
     */
    public frmMedico() {
        this("Dr. Médico");
    }
    
    public frmMedico(String nombreMedico) {
        this.nombreMedico = nombreMedico;
        initComponents();
        cargarDatosEjemplo();
        lBienvenida.setText("Bienvenido, " + nombreMedico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lBienvenida = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasAgendadas = new javax.swing.JTable();
        btnAtender = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitasAtendidas = new javax.swing.JTable();
        btnVerDetalles = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Médico");

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("Sistema de Gestión Médica");

        lBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lBienvenida.setText("Bienvenido, Dr. Médico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(lBienvenida)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo)
                    .addComponent(lBienvenida))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tablaCitasAgendadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAgendadas.setRowHeight(25);
        jScrollPane1.setViewportView(tablaCitasAgendadas);

        btnAtender.setBackground(new java.awt.Color(60, 179, 113));
        btnAtender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("Atender Cita");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(new java.awt.Color(100, 149, 237));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtender)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtender)
                    .addComponent(btnRefrescar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("📅 Citas Agendadas", jPanel2);

        tablaCitasAtendidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAtendidas.setRowHeight(25);
        jScrollPane2.setViewportView(tablaCitasAtendidas);

        btnVerDetalles.setBackground(new java.awt.Color(100, 149, 237));
        btnVerDetalles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalles.setText("Ver Detalles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVerDetalles)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetalles)
                .addContainerGap())
        );

        jTabbedPane1.addTab("✓ Citas Atendidas", jPanel3);

        btnCerrarSesion.setBackground(new java.awt.Color(220, 20, 60));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        atenderCita();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarCitasAgendadas();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        verDetalles();
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMedico().setVisible(true));
    }
    
    // MÉTODOS PERSONALIZADOS
    private void cargarDatosEjemplo() {
        citasAgendadas = new ArrayList<>();
        citasAgendadas.add(new CitaConcreta("C001", LocalDate.of(2026, 1, 8), Time.valueOf("09:00:00"), 
            "Chequeo general", "Agendada", "Juan Pérez"));
        citasAgendadas.add(new CitaConcreta("C002", LocalDate.of(2026, 1, 8), Time.valueOf("10:30:00"), 
            "Dolor abdominal", "Agendada", "María García"));
        citasAgendadas.add(new CitaConcreta("C003", LocalDate.of(2026, 1, 9), Time.valueOf("14:00:00"), 
            "Control de presión", "Agendada", "Carlos López"));
        
        citasAtendidas = new ArrayList<>();
        citasAtendidas.add(new CitaConcreta("C100", LocalDate.of(2026, 1, 5), Time.valueOf("09:00:00"), 
            "Dolor de cabeza", "Atendida", "Pedro Sánchez"));
        citasAtendidas.add(new CitaConcreta("C101", LocalDate.of(2026, 1, 6), Time.valueOf("15:00:00"), 
            "Control diabetes", "Atendida", "Laura Fernández"));
        
        cargarCitasAgendadas();
        cargarCitasAtendidas();
    }
    
    private void cargarCitasAgendadas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCitasAgendadas.getModel();
        modelo.setRowCount(0);
        for (CitaConcreta cita : citasAgendadas) {
            modelo.addRow(new Object[]{
                cita.getIdCita(),
                cita.getFecha(),
                cita.getHora(),
                cita.getNombrePaciente(),
                cita.getMotivo(),
                cita.getEstado()
            });
        }
    }
    
    private void cargarCitasAtendidas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCitasAtendidas.getModel();
        modelo.setRowCount(0);
        for (CitaConcreta cita : citasAtendidas) {
            modelo.addRow(new Object[]{
                cita.getIdCita(),
                cita.getFecha(),
                cita.getHora(),
                cita.getNombrePaciente(),
                cita.getMotivo(),
                cita.getEstado()
            });
        }
    }
    
    private void atenderCita() {
        int fila = tablaCitasAgendadas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para atender");
            return;
        }
        
        String idCita = (String) tablaCitasAgendadas.getValueAt(fila, 0);
        String paciente = (String) tablaCitasAgendadas.getValueAt(fila, 3);
        
        frmAtenderCita ventana = new frmAtenderCita(idCita, paciente);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(this);
        
        // Mover cita a atendidas
        CitaConcreta cita = citasAgendadas.get(fila);
        cita.setEstado("Atendida");
        citasAtendidas.add(cita);
        citasAgendadas.remove(fila);
        
        cargarCitasAgendadas();
        cargarCitasAtendidas();
    }
    
    private void verDetalles() {
        int fila = tablaCitasAtendidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para ver detalles");
            return;
        }
        
        CitaConcreta cita = citasAtendidas.get(fila);
        String detalles = String.format(
            "DETALLES DE LA CITA\n\n" +
            "ID: %s\n" +
            "Paciente: %s\n" +
            "Fecha: %s\n" +
            "Hora: %s\n" +
            "Motivo: %s\n" +
            "Estado: %s",
            cita.getIdCita(), cita.getNombrePaciente(), cita.getFecha(), 
            cita.getHora(), cita.getMotivo(), cita.getEstado()
        );
        
        JOptionPane.showMessageDialog(this, detalles, "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void cerrarSesion() {
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea cerrar sesión?", 
            "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            frmlogin login = new frmlogin();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTable tablaCitasAgendadas;
    private javax.swing.JTable tablaCitasAtendidas;
    // End of variables declaration//GEN-END:variables
}

// Clase auxiliar
class CitaConcreta extends Cita {
    private String nombrePaciente;
    
    public CitaConcreta(String idCita, LocalDate fecha, Time hora, String motivo, String estado, String nombrePaciente) {
        super(idCita, fecha, hora, motivo, estado);
        this.nombrePaciente = nombrePaciente;
    }
    
    public String getNombrePaciente() { return nombrePaciente; }
    
    @Override
    public void confirmar() { this.estado = "Confirmada"; }
    
    @Override
    public void cancelar(String motivo) { this.estado = "Cancelada"; }
    
    @Override
    public void reprogramar(LocalDate nuevaFecha) { this.fecha = nuevaFecha; }
}