/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;
import pack_gui.frmlogin;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class frmregistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmregistro.class.getName());
    private HashMap<String, String> mapaUsuarios = new HashMap<>();
    private static final String HIDEN_KEY = "2406200611012026"; //Nota: La contraseña si permite mayúsculas y es CaseSensitive
    /**
     * Creates new form frmregistro
     */
    public frmregistro() {
        initComponents();
        cargarDesdeCSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pRegistro = new javax.swing.JPanel();
        tNombre = new javax.swing.JTextField();
        tApellido = new javax.swing.JTextField();
        cTipoUsuario = new javax.swing.JComboBox<>();
        pContrasena1 = new javax.swing.JPasswordField();
        bRegistrarUsuario = new javax.swing.JButton();
        iRegistro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lRegistro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro-Vital Core");

        pRegistro.setBackground(java.awt.SystemColor.control);

        tNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        tNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNombreMouseClicked(evt);
            }
        });
        tNombre.addActionListener(this::tNombreActionPerformed);

        tApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));

        cTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Paciente", "Doctor", "Farmaceutico" }));
        cTipoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Usuario"));
        cTipoUsuario.addActionListener(this::cTipoUsuarioActionPerformed);

        pContrasena1.setText("jPasswordField1");
        pContrasena1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        bRegistrarUsuario.setBackground(new java.awt.Color(51, 153, 255));
        bRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrarUsuario.setText("Registrar Usuario");
        bRegistrarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegistrarUsuarioMouseClicked(evt);
            }
        });
        bRegistrarUsuario.addActionListener(this::bRegistrarUsuarioActionPerformed);

        iRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crear-cuenta.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        lRegistro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lRegistro.setText("Registro");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addComponent(lRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRegistro)
                    .addComponent(jButton1))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout pRegistroLayout = new javax.swing.GroupLayout(pRegistro);
        pRegistro.setLayout(pRegistroLayout);
        pRegistroLayout.setHorizontalGroup(
            pRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iRegistro)
                .addGap(111, 111, 111))
            .addGroup(pRegistroLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pRegistroLayout.createSequentialGroup()
                        .addComponent(cTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRegistrarUsuario)
                        .addGap(9, 9, 9))
                    .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pRegistroLayout.setVerticalGroup(
            pRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iRegistro)
                .addGap(26, 26, 26)
                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistrarUsuario))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String encriptar(String datos) {
        try {
            SecretKeySpec secretKey = new SecretKeySpec(HIDEN_KEY.getBytes(), "AES");
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            byte[] datosEncriptados = cipher.doFinal(datos.getBytes());
            return Base64.getEncoder().encodeToString(datosEncriptados);
        } catch (Exception e) {
            return null;
        }
    }
    
    private void cargarDesdeCSV() {
        java.io.File archivo = new java.io.File("usuarios.csv");
        if (!archivo.exists()) {
            return;
        }

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String line;
            boolean firstLine = true;
            while ((line = br.readLine()) != null) {
                if (firstLine) {
                    firstLine = false;
                    continue;
                }

                String[] partes = line.split(",");
                if (partes.length == 2) {
                    mapaUsuarios.put(partes[0], partes[1]);
                }
            }
        } catch (java.io.IOException e) {
            System.out.println("Error al cargar datos: " + e.getMessage());
        }
    }
    
    private void guardarEnCSV(){
        try (java.io.FileWriter fw = new java.io.FileWriter("usuarios.csv");
            java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {
        
                pw.println("Usuario,Contrasena");
        
                for (java.util.Map.Entry<String, String> entry : mapaUsuarios.entrySet()) {
                    pw.println(entry.getKey() + "," + entry.getValue());
                }
        
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado y base de datos actualizada.");
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar archivo: " + e.getMessage());
        }
    }
    
    private void cTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTipoUsuarioActionPerformed

    private void bRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRegistrarUsuarioActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void bRegistrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegistrarUsuarioMouseClicked

        String nombre = tNombre.getText().trim();
        String apellido = tApellido.getText().trim();
        String tipo = cTipoUsuario.getSelectedItem().toString();
        String password = new String (pContrasena1.getPassword());  //Aquí se encontraba el error al intentar transformar a String un arreglo de caracteres dierctamente
        //Se propone un requerimiento de verificación básico para asegurarse que las personas con credenciales de médico sean las correctas
        String claveFarm = "f4rM4c3ut1c0.5512";
        String claveMed = "m3d1C04325";
if (nombre.isEmpty() || apellido.isEmpty() || password.isEmpty() || tipo.equals("Seleccionar")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }
        if (tipo.equals("Doctor")){
            String userCodeMed= JOptionPane.showInputDialog(this, "Ingrese el código de verificación correspondiente", "VERIFICADOR DE IDENTIDAD",JOptionPane.QUESTION_MESSAGE).toString();
            if (!userCodeMed.equals(claveMed)){
                javax.swing.JOptionPane.showMessageDialog(this, "La clave ingresada es incorrecta");
                return;
            }
        } else if(tipo.equals("Farmaceutico")){
            String userCodeFarm= JOptionPane.showInputDialog(this, "Ingrese el código de verificación correspondiente", "VERIFICADOR DE IDENTIDAD",JOptionPane.QUESTION_MESSAGE).toString();
            if (!userCodeFarm.equals(claveFarm)){
                javax.swing.JOptionPane.showMessageDialog(this, "La clave ingresada es incorrecta");
                return;
            }
        }

        String usuarioID = (nombre.substring(0, 1) + "." + apellido + "_" + tipo + "@gestionmedica.gob.ec").toLowerCase();
        String claveEncriptada = encriptar(password);

        mapaUsuarios.put(usuarioID, claveEncriptada);
        guardarEnCSV();
        javax.swing.JOptionPane.showMessageDialog(this, "Estimado, el usuario generado para su cuenta es:\t" + usuarioID);
        tNombre.setText("");
        tApellido.setText("");
        pContrasena1.setText("");
        cTipoUsuario.setSelectedIndex(0);
    }//GEN-LAST:event_bRegistrarUsuarioMouseClicked

    private void tNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        frmlogin ventanaLogin = new frmlogin(); 
        ventanaLogin.setVisible(true); 
        ventanaLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new frmregistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistrarUsuario;
    private javax.swing.JComboBox<String> cTipoUsuario;
    private javax.swing.JLabel iRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lRegistro;
    private javax.swing.JPasswordField pContrasena1;
    private javax.swing.JPanel pRegistro;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}